version: '3'

services:

  react:
    command: >
      sh -c "npm run build &&
             gulp build"
    #remove this later
    ports: "2000:2000"
    env_file:
      - ./env/prod.env
    restart: always