version: '3'

services:

  react:
    container_name: react

    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /react-new/node_modules
      - .:/react-new
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"